[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[ruby]
symbol = " "

[rust]
symbol = " "

[custom.docker]
command = "echo  v$(docker version --format '{{.Server.Version}}')"
files = ["Dockerfile"]
style = "bold #0db7ed"

[custom.r]
command = 'echo "R v${$(R --version):10:5}"'
directories = ["R"]
extensions = ["R", "r"]
style = "bold #919198"
