name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        env:
          TERM: xterm-256color
        run: |
          # create dummy files to skip interactive steps (SSH/Colima)
          mkdir -p ~/.ssh ~/.colima/default
          touch ~/.ssh/id_ed25519 ~/.colima/default/colima.yaml Brewfile
          
          # run bootstrap script
          ./bootstrap.sh

      - name: Verify
        shell: zsh {0}
        run: |
          # Check if ~/bin and ~/.zsh are valid symbolic links
          if [ -L ~/bin ] && [ -L ~/.zsh ]; then
            echo "✔ Dotfiles linked successfully"
          else
            echo "❌ Linking failed"
            exit 1
          fi